name: macOS

on: [ push, pull_request ]


jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build APK
        run: ./gradlew build

      - uses: actions/upload-artifact@v2
        with:
          name: macos
          path: app/build/outputs/apk/prod/release/
