name: Ubuntu

on: [ push, pull_request ]


jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Build APK
        run: ./gradlew build

      - uses: actions/upload-artifact@v2
        with:
          name: ubuntu
          path: app/build/outputs/apk/prod/release/
